[package]
name = "egui-selectable-table"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.29.1", default-features = false, features = ["rayon"] }
egui_extras = { version = "0.29.1", default-features = false }
rayon = "1.10.0"
