[package]
name = "egui-selectable-table"
version = "0.6.0"
edition = "2024"
description = """
A library for egui to create tables with draggable cell and row selection.
"""
readme = "README.md"
homepage = "https://github.com/TheRustyPickle/egui-selectable-table"
repository = "https://github.com/TheRustyPickle/egui-selectable-table"
license = "MIT"
keywords = ["drag", "egui", "row", "selectable-table", "table"]
categories = ["gui"]
exclude = ["/.github", "/demo"]

[package.metadata.docs.rs]
all-features = true
features = ["fuzzy-matching"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ahash = "0.8.12"
egui = { version = "0.35", default-features = false, features = ["rayon"] }
egui_extras = { version = "0.35", default-features = false }
nucleo-matcher = { version = "0.3.1", optional = true }
rayon = "1.12.0"

[features]
default = []
fuzzy-matching = ["dep:nucleo-matcher"]

[lints.clippy]
enum_glob_use = { level = "deny", priority = 2 }
nursery = { level = "deny", priority = 0 }
pedantic = { level = "deny", priority = 1 }
perf = { level = "deny", priority = 3 }
style = { level = "deny", priority = 4 }
unwrap_used = { level = "deny", priority = 5 }

# might be useful to enable in the future
expect_used = { level = "allow", priority = 6 }
missing_panics_doc = { level = "allow", priority = 7 }
struct_excessive_bools = { level = "allow", priority = 8 }

[lints.rust]
unsafe_code = "forbid"
